### ISSUE TITLE
Setup the CI Pipeline with Pytest

### ISSUE THREAD

**Issue by frinzekt** [codersforcauses/software-engineering-practices-demo#1]
## Description
Setup the CI pipeline with Pytest.

This will enable future pull requests to run automated testing to make sure that changes that are introduced are properly tested.

## Answer (this usually does not exist in the real world)
**For simplicity, this is included so anybody can do it**

### CI Pipeline Github Action
create a new folder called `.github` and create a new file called `ci.yml`. This is as per https://github.com/features/actions 
Add this content
```yml
name: Python package

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: false
        default: "warning"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8] # you can add more python version to test it in

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest
```

## Dependencies

1. Add a file called `requirements.txt` with content

```
pytest # test runner
pytest-xdist # parallelisation
```

2. Add the file called `pytest.ini` with content

```
[pytest]
python_files = tests.py test_*.py *_tests.py
```
